config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :tables do
    resources :tasks
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 3 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :table
  validates :title, presence: true,
                    length: { minimum: 3 }
  validate :is_valid_date?

  private

  def is_valid_date?
    if Date.today> finish_date || start_date>finish_date || table.creation_date > start_date
      errors.add(:finish_date, 'invalid date')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = Table.all
  end

  def show
    @table = Table.find(params[:id])
  end

  def new
    @table = Table.new
  end

  def edit
    @table = Table.find(params[:id])
  end

  def create
    @table = Table.new(table_params)

    if @table.save
      redirect_to @table
    else
      render 'new'
    end
  end

  def update
    @table = Table.find(params[:id])

    if @table.update(table_params)
      redirect_to @table
    else
      render 'edit'
    end
  end

  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    redirect_to tables_path
  end

  private
  def table_params
    params.require(:table).permit(:title, :description, :state, :creation_date)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def edit
    @table = Table.find(params[:table_id])
    @task = @table.tasks.find(params[:id])
  end

  def create
    @table = Table.find(params[:table_id])
    @task = @table.tasks.create(task_params)
    redirect_to table_path(@table)
  end

  def destroy
    @table = Table.find(params[:table_id])
    @task = @table.tasks.find(params[:id])
    @task.destroy
    redirect_to table_path(@table)
  end

  def update
   @table = Table.find(params[:table_id])
   @task = @table.tasks.find(params[:id])
   if @task.update(task_params)
     redirect_to table_path(@table)
   else
     render 'edit'
   end
 end

  private
    def task_params
      params.require(:task).permit(:title, :details, :start_date, :finish_date, :state)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do - Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <header>
      <nav class="navbar navbar-expand-md bg-dark navbar-dark ">
        <a class="navbar-brand">ROR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Index", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Projects", tables_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </nav>
      <div class=" title">
        <h3>To Do Management</h3>
      </div>
    </header>
    <br>

    <%= yield %>
    <p></p>
    <!-- Final de Pagina - Footer -->
  <footer class="container">
    <p>Diseñada por: <b><i>Daissi Bibiana Gonzalez Roldan</i></b>
      <br>Correo: dbgroldan@gmail.com
      <br><b><i>CopyRight<br>2018</i></b></p>
  </footer>

  </body>
</html>

app/views/tables/edit.html.erb
<div class="container">
  <h1>Edit Project Table</h1>
  <%= form_with(model: @table, local: true) do |form| %>

    <% if @table.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@table.errors.count, "error") %> prohibited
          this project table from being saved:
        </h2>
        <ul>
          <% @table.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%=form.label :project_state_ %>
      <%= form.select(:state) do %>
        <% [['In progress', 0], ['Completed', 1], ['Not Started',2]].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <br>
</div>

app/views/tables/index.html.erb
<div class="container">
  <h1>Created Projects </h1>
  <table class="table">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>State</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>

    <% @tables.each do |table| %>
      <tr>
        <td><%= table.title %></td>
        <td><%= table.description %></td>
        <td>
          <%states = ['In progress', 'Completed', 'Not Started'] %>
          <%=states[table.state] %>
        </td>
        <td><%=table.creation_date %></td>
        <td><%= link_to 'Show', table_path(table) %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table_path(table),
                method: :delete,
                data: { confirm: 'Are you sure you want delete this project?' } %></td>
      </tr>
    <% end %>
  </table>
  <%= button_to "New Project Table", { :action => "new" }, :method => :get %>
  <br>
</div>

app/views/tables/new.html.erb
<div class="container">
  <h1>New Project Table</h1>
  <%= form_with scope: :table, url: tables_path, local: true do |form| %>

    <% if @table.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@table.errors.count, "error") %> prohibited
          this project table from being saved:
        </h2>
        <ul>
          <% @table.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%=form.label :project_state_ %>
      <%= form.select(:state) do %>
        <% [['In progress', 0], ['Completed', 1], ['Nos Started',2]].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
    </p>

    <p>

    </p>
      <%=form.label :created_date %>
      <%= form.date_field :creation_date ,value: Date.today.strftime("%Y-%m-%d")%>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <br>
</div>

app/views/tables/show.html.erb
<div class="container">
<div class="row">
  <!-- Project Info-->
  <div class="col-md-8">
    <br><h2>Project</h2>
    <p>
      <strong>Title:</strong>
      <%= @table.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @table.description %>
    </p>

    <p>
      <strong>Project State:</strong>
      <% states=['In Progress','Completed', 'Not Started']%>
      <%= states[@table.state] %>
    </p>

    <p>
      <strong>Creation Date:</strong>
      <%= @table.creation_date%>
    </p>
  </div>

<% unless @table.state == 1 || @table.state == 2%>
<!--- Adding Tasks -->
  <div class="col-md-4">
    <h3>Add Task:</h3>
    <%= form_with(model: [ @table, @table.tasks.build ], local: true) do |form| %>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <br>
        <%= form.label :description %><br>
        <%= form.text_area :details %>
        <br>
        <%=form.label :start_date %>
        <%= form.date_field :start_date ,value: Date.today.strftime("%Y-%m-%d")%>
        <br>
        <%=form.label :finish_date %>
        <%= form.date_field :finish_date%>
        <br>
          <%=form.label :task_state_ %>
          <%= form.select(:state) do %>
            <% [['Do', 0], ['Doing', 1], ['Done',2]].each do |c| -%>
              <%= content_tag(:option, c.first, value: c.last) %>
            <% end %>
          <% end %>
        <br>
        <%= form.submit %>
    <% end %>
  </div>
  </div>
</div>
<% end %>

<br>
<!---Info table -->
<div class="container">
  <div class="row">
    <!-- Show Tasks -->
    <div class="tab list to-do">
      <h3>To Do</h3>
      <% @table.tasks.each do |task| %>
        <% if task.state == 0 %>
          <div class="tab task">
            <strong>
              Title:
              <%= task.title %>
            </strong>
            <br>
              <strong>Details:</strong>
              <%= task.details %>
            <br>
              <strong>Start date:</strong>
              <%= task.start_date%>
            <br>
              <strong>Finish date.:</strong>
              <%= task.finish_date %>
            <p>
            <%= button_to "Edit", edit_table_task_path(@table, task), :method => :get %>
            <%= button_to 'Delete', [task.table, task],
                           method: :delete,
                           data: { confirm: 'Are you sure you want delete this task?' } %>
            </p>
            </div>
        <% end %>
      <% end %>
    </div>

    <div class="tab list doing">
      <h3>Doing</h3>
      <% @table.tasks.each do |task| %>
        <% if task.state == 1 %>
          <div class="tab task">
            <strong>
              Title:
              <%= task.title %>
            </strong>
            <br>
              <strong>Details:</strong>
              <%= task.details %>
            <br>
              <strong>Start date:</strong>
              <%= task.start_date%>
            <br>
              <strong>Finish date.:</strong>
              <%= task.finish_date %>
            <p>
            <%= button_to "Edit", edit_table_task_path(@table, task), :method => :get %>
            <%= button_to 'Delete', [task.table, task],
                           method: :delete,
                           data: { confirm: 'Are you sure you want delete this task?' } %>
            </p>
            </div>
        <% end %>
      <% end %>
    </div>

    <div class="tab list done">
      <h3>Done</h3>

      <% @table.tasks.each do |task| %>
        <% if task.state == 2 %>
          <div class="tab task">
            <strong>
              Title:
              <%= task.title %>
            </strong>
            <br>
              <strong>Details:</strong>
              <%= task.details %>
            <br>
              <strong>Start date:</strong>
              <%= task.start_date%>
            <br>
              <strong>Finish date.:</strong>
              <%= task.finish_date %>
            <p>
            <%= button_to "Edit", edit_table_task_path(@table, task), :method => :get %>
            <%= button_to 'Delete', [task.table, task],
                           method: :delete,
                           data: { confirm: 'Are you sure you want delete this task?' } %>
            </p>
            </div>
        <% end %>
      <% end %>

    </div>
  </div>
  <br>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task </h1>
  <%= form_with(model: [ @table, @task], local: true) do |form| %>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <br>
    <%= form.label :description %><br>
    <%= form.text_area :details %>
    <br>
    <%=form.label :start_date %>
    <%= form.date_field :start_date %>
    <br>
    <%=form.label :finish_date %>
    <%= form.date_field :finish_date%>
    <br>
      <%=form.label :task_state_ %>
      <%= form.select(:state) do %>
        <% [['Do', 0], ['Doing', 1], ['Done',2]].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
      <% end %>
    <br>
    <%= form.submit %>
  <% end %>
  <br>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="container col-sm-6">
      <h1>Kanban</h1>
      <p>Kanban (signboard or billboard in Japanese) is a scheduling system for lean manufacturing and just-in-time manufacturing (JIT).Taiichi Ohno, an industrial engineer at Toyota, developed kanban to improve manufacturing efficiency. Kanban is one method to achieve JIT. The system takes its name from the cards that track production within a factory. For many in the automotive sector, kanban is known as the "Toyota nameplate system" and as such the term is not used by some other automakers.</p>
    </div>
    <div class="container col-sm-4">
      <h3>To Do Management </h3>
      <p>In this way you have that the application is a method to organize daily activities and even team projects, so you can start with:</p>
      <%= button_to "New Project Table", { :controller =>"tables", :action => "new" }, :method => :get %>
      <br>
    </div>
  </div>
</div>